fix: delete hpsi before new one in operator.h
deepmodeling/abacus-develop pull request #1196
Opened 2022-09-02 08:55 UTC by pxlxingliang

2022-09-02 09:06 UTC, dyzheng approved these changes

2022-09-03 03:13 UTC, caic99 requested changes

2022-09-03 03:13 UTC, caic99 commented on source/module_hamilt/operator.h
> +        if(this->hpsi != nullptr) delete this->hpsi;
```suggestion
        if(this->hpsi != nullptr) 
        {
            delete this->hpsi;
            this->hpsi = nullptr;
        }
```

2022-09-05 02:30 UTC, caic99 approved these changes

2022-09-05 02:30 UTC, merged