feature : add xc_temperature input keyword for finite T functionals
deepmodeling/abacus-develop pull request #1227
Opened 2022-09-13 09:22 UTC by wenfei-li

2022-09-13 12:25 UTC, caic99 requested changes, later dismissed

2022-09-13 12:25 UTC, caic99 commented on docs/input-main.md
> +#### xc_termperature
```suggestion
#### xc_temperature
```

2022-09-13 12:25 UTC, caic99 commented on docs/input-main.md
> +- **Default** : 0.0
Do we need an unit for this?

2022-09-13 12:25 UTC, caic99 commented on source/module_xc/xc_functional.cpp
> +            xc_func_set_ext_params(&funcs.back(), parameter_finitet);
```suggestion
        if(id == XC_LDA_XC_KSDT || id == XC_LDA_XC_CORRKSDT || id == XC_LDA_XC_GDSMFB) //finite temperature XC functionals
        {
            add_func(id);
            double parameter_finitet[1] = {GlobalV::XC_TEMPERATURE};
            xc_func_set_ext_params(&funcs.back(), parameter_finitet);
```

2022-09-13 12:45 UTC, wenfei-li commented on docs/input-main.md
> +- **Default** : 0.0
> Do we need a unit for this?

indeed. working on it

2022-09-15 02:28 UTC, Qianruipku approved these changes

2022-09-15 06:57 UTC, merged