Build: abacus can compile pw version with cmake
deepmodeling/abacus-develop pull request #1397
Opened 2022-10-15 09:06 UTC by Qianruipku

1. It is added to the workflows of github
2. delete temporary tests in src_pw

2022-10-16 10:44 UTC, caic99 requested changes
@baixiaokuang @mohanchen As we mentioned in the last meeting, further discussion on whether we need a pw-basis-only abacus executable and its necessity should be carried out.
@Qianruipku If there are any updates on this topic, I'll let you know.

2022-10-16 10:44 UTC, caic99 commented on CMakeLists.txt
> +endif()
What's the point assigning different binary name?

2022-10-16 10:44 UTC, caic99 commented on source/module_gint/CMakeLists.txt
> +if(ENABLE_LCAO)
For these libraries only in LCAO basis, you should keep it out in the root CMakeLists.txt .

2022-10-16 10:44 UTC, caic99 commented on CMakeLists.txt
> +
Please note the indentations.

2022-10-16 13:58 UTC, Qianruipku commented on CMakeLists.txt
> +
Ok

2022-10-24 08:13 UTC, caic99 approved these changes
After conversation with @baixiaokuang , we think this solution is able to keep the development of planewave module independent with LCAO.

2022-10-24 08:14 UTC, merged