Fix: stresses are output too close when they are too large
deepmodeling/abacus-develop pull request #1642
Opened 2022-12-06 11:43 UTC by Qianruipku

At a temperature of 1000 eV, stresses are so large that the log file cannot print them well. 
Before fix:
x-special/nautilus-clipboard
copy
file:///home/qianrui/%E6%A1%8C%E9%9D%A2/%E5%A4%AA%E8%BF%91%E4%B9%90.png
After fix:
![改后](https://user-images.githubusercontent.com/76200646/205901987-8d0070d4-9b80-49a5-ba02-5b7b22a90900.png)

2022-12-08 04:04 UTC, dyzheng approved these changes

2022-12-08 04:06 UTC, dyzheng requested changes
Maybe better solution is using scientific notation. 
Too many space will make the output line too long.

2022-12-08 07:25 UTC, Qianruipku commented
> Maybe better solution is using scientific notation. Too many space will make the output line too long.

![image](https://user-images.githubusercontent.com/76200646/206381964-d32c7e8a-f9b2-4244-96a5-9547ea3156a8.png)
![image](https://user-images.githubusercontent.com/76200646/206383738-80bd3132-9c52-4f4a-bcaf-4aca0db99e4c.png)
In fact, the running_scf.log file does not use the scientific notation and has an average width of 70 spaces.
I think it is more beautiful to give stress output a width of 70 spaces rather than 40.

Screen output uses the scientific notation and I will recover the original length.

2022-12-09 14:15 UTC, dyzheng approved these changes

2022-12-09 14:16 UTC, merged