feature: surpport define kspacing for a/b/c separately
deepmodeling/abacus-develop pull request #2324
Opened 2023-04-25 07:24 UTC by pxlxingliang

2023-04-25 14:08 UTC, dyzheng commented on source/module_io/input.cpp
> +            //read 3 values
line 691 - 719 should refactor to a functional and add UnitTest for this function independent.

2023-04-25 14:08 UTC, dyzheng commented on source/module_io/input.cpp
> +                    ModuleBase::WARNING_QUIT("Input", "kspacing should be > 0");
Don't WARNING_QUIT during reading.

2023-04-25 14:08 UTC, dyzheng commented on source/module_io/input.cpp
> +    for (int i=0;i<3;i++){
maybe you can assert :
```
double maximum=0, multiply=1;
for(i=0;i<3;i++)
{
    maximum = std::max(std::abs(kspacing[i], maximum));
    multiply *= kspacing[i];
    if (kspacing[i] < 0.0)
    {
        ModuleBase::WARNING_QUIT("Input", "kspacing must > 0");
    }
}
if(maximum > small && multiple < small)
{WARNING_QUIT();}
```

2023-04-25 14:14 UTC, sunliang98 commented
Maybe it's better to add an integrate test with defining kspacing for a/b/c separately.

2023-04-25 14:23 UTC, dyzheng commented
> Maybe it's better to add an integrate test with defining kspacing for a/b/c separately.

It is okay to add Integrate test, but UnitTest is better than Integrate test.

2023-04-26 01:13 UTC, hongriTianqi commented on source/module_io/input.cpp
> +                    ModuleBase::WARNING_QUIT("Input", "kspacing should be > 0");
Agree: checking in input parameters should be put in the function Input::Check()

2023-04-26 01:18 UTC, hongriTianqi requested changes

2023-04-26 01:18 UTC, hongriTianqi commented on source/module_cell/klist.cpp
> +    else if (GlobalV::KSPACING[0] > 0.0)
Should we make sure that GlobalV::KSPACING[1] > 0.0 and Global::KSPACING[2] > 0.0?

2023-04-26 01:21 UTC, hongriTianqi requested changes

2023-04-26 01:21 UTC, hongriTianqi commented on source/module_cell/klist.cpp
> +        int nk3 = max(1,static_cast<int>(b3 * ModuleBase::TWO_PI / GlobalV::KSPACING[2] / GlobalC::ucell.lat0 + 1));
The correspongding unit test for K_Vectors::read_kpoints should be added for this functionality.

2023-04-26 09:13 UTC, dyzheng approved these changes

2023-04-26 09:28 UTC, hongriTianqi approved these changes

2023-04-26 10:15 UTC, merged