Dm mixing
deepmodeling/abacus-develop pull request #2442
Opened 2023-05-11 20:11 UTC by PeizeLin

2023-05-12 01:06 UTC, maki49 approved these changes

2023-05-12 01:06 UTC, maki49 commented on source/module_io/input.cpp
> +    exx_mixing_beta = 1.0;
Please modify `module_io/tests`(which failed on CI) corresponding to the change of default value. Thanks~

2023-05-12 04:50 UTC, dyzheng commented
Title of this PR should be modified to "Feature: ...", please add detaild description.

2023-05-12 04:59 UTC, dyzheng requested changes

2023-05-12 04:59 UTC, dyzheng commented on source/module_ri/Mix_DMk_2D.cpp
> +
Please add unit tests for new cpp files.

2023-05-12 04:59 UTC, dyzheng commented on source/module_ri/Mix_DMk_2D.h
> +
Please add unit tests for new cpp files.

2023-05-12 04:59 UTC, dyzheng commented on source/module_ri/Mix_Data.hpp
> +#define MIX_DATA_HPP
Please add unit tests for new hpp files.

2023-05-12 04:59 UTC, dyzheng commented on source/module_esolver/esolver_ks_lcao_elec.cpp
> +		// set initial parameter for mix_DMk_2D
please add annotations for this code block, this has changed a file without UT, such as GPT's annotation:
```
This code block checks if a certain flag (cal_exx) is set in a global variable (exx_info.info_global) and configures a 2D mixing object (mix_DMk_2D) accordingly. If the flag is set, it sets the number of k-points in the mixing object to the value in another global variable (kv.nks). If another flag (separate_loop) is set, it checks if a mixing parameter (mixing_beta_for_loop1) is set to 1.0 and sets the mixing mode of the object to "No" if it is, or "Plain" with the mixing parameter value if it is not. If the separate_loop flag is not set, it checks the mixing mode of another global object (CHR_MIX) and sets the mixing mode of the mixing object to "Plain" or "Pulay" accordingly, with the mixing parameter value from CHR_MIX. If the mixing mode is not recognized, it throws an exception with an error message.
```

2023-05-12 04:59 UTC, dyzheng commented on source/module_ri/Mix_DMk_2D.cpp
> +Mix_DMk_2D &Mix_DMk_2D::set_nks(const int nks)
Please add annotations for new files, should be doxgen format.

2023-05-12 05:01 UTC, dyzheng commented on source/module_io/input.cpp
> +    exx_mixing_beta = 1.0;
The default value has been changed, how about documentation?

2023-05-12 05:49 UTC, maki49 commented
@PeizeLin has difficulties in adding unit tests.  (https://github.com/deepmodeling/abacus-develop/issues/2306). I will try to help for this.

2023-05-16 01:59 UTC, dyzheng approved these changes
please write detail title and decription for this PR @PeizeLin

2023-05-16 01:59 UTC, dyzheng commented on source/module_ri/Mix_DMk_2D.h
> +class Mix_DMk_2D
```suggestion
/**
 * @class Mix_DMk_2D
 * @brief Class for mixing density matrix in DFT code.
 */
class Mix_DMk_2D
```

2023-05-16 01:59 UTC, dyzheng commented on source/module_ri/Mix_DMk_2D.h
> +	Mix_DMk_2D &set_nks(const int nks, const bool gamma_only_in);
```suggestion
/**
     * @brief Sets the number of k-points and gamma_only flag.
     * @param nks Number of k-points.
     * @param gamma_only_in Flag indicating if only gamma point is mixed.
     * @return Reference to the current object.
     */
	Mix_DMk_2D &set_nks(const int nks, const bool gamma_only_in);
```

2023-05-16 01:59 UTC, dyzheng commented on source/module_ri/Mix_DMk_2D.h
> +	Mix_DMk_2D &set_mixing_mode(const Mixing_Mode mixing_mode);
```suggestion
/**
     * @brief Sets the mixing mode.
     * @param mixing_mode Mixing mode.
     * @return Reference to the current object.
     */
	Mix_DMk_2D &set_mixing_mode(const Mixing_Mode mixing_mode);
```

2023-05-16 01:59 UTC, dyzheng commented on source/module_ri/Mix_DMk_2D.h
> +    Mix_DMk_2D& set_mixing_beta(const double mixing_beta);
```suggestion
/**
     * @brief Sets the mixing beta.
     * @param mixing_beta Mixing beta.
     * @return Reference to the current object.
     */
    Mix_DMk_2D& set_mixing_beta(const double mixing_beta);
```

2023-05-16 01:59 UTC, dyzheng commented on source/module_ri/Mix_DMk_2D.h
> +    template<typename ChgMix>
```suggestion
/**
     * @brief Sets the Pulay mixing coefficient.
     * @tparam ChgMix Type of the charge mixing coefficient.
     * @param iter Iteration number.
     * @param chr_mix Charge mixing coefficient.
     * @return Reference to the current object.
     */
    template<typename ChgMix>
```

2023-05-16 01:59 UTC, dyzheng commented on source/module_ri/Mix_DMk_2D.h
> +	void mix(const std::vector<ModuleBase::matrix> &dm, const bool flag_restart);
```suggestion
/**
     * @brief Mixes the density matrix.
     * @param dm double Density matrix.
     * @param flag_restart Flag indicating if it is a restart.
     */
	void mix(const std::vector<ModuleBase::matrix> &dm, const bool flag_restart);

```

2023-05-16 01:59 UTC, dyzheng commented on source/module_ri/Mix_DMk_2D.h
> +	void mix(const std::vector<ModuleBase::ComplexMatrix> &dm, const bool flag_restart);
```suggestion
/**
     * @brief Mixes the complex density matrix.
     * @param dm Complex density matrix.
     * @param flag_restart Flag indicating if it is a restart.
     */
	void mix(const std::vector<ModuleBase::ComplexMatrix> &dm, const bool flag_restart);
```

2023-05-16 01:59 UTC, dyzheng commented on source/module_ri/Mix_DMk_2D.h
> +	std::vector<const ModuleBase::matrix*> get_DMk_gamma_out() const;
```suggestion
/**
     * @brief Returns the gamma density matrix.
     * @return Vector of pointers to gamma density matrices.
     */
	std::vector<const ModuleBase::matrix*> get_DMk_gamma_out() const;
```

2023-05-16 01:59 UTC, dyzheng commented on source/module_ri/Mix_DMk_2D.h
> +	std::vector<const ModuleBase::ComplexMatrix*> get_DMk_k_out() const;
```suggestion
/**
     * @brief Returns the k-point density matrix.
     * @return Vector of pointers to k-point density matrices.
     */
	std::vector<const ModuleBase::ComplexMatrix*> get_DMk_k_out() const;
```

2023-05-16 01:59 UTC, dyzheng commented on source/module_ri/Mix_Data.hpp
> +template<typename Tdata>
```suggestion
/**
 * @brief Mixes the input data according to the set mixing mode.
 * @param data_in Input data to be mixed.
 * @param flag_restart Flag indicating if it is a restart.
 */
template<typename Tdata>
```

2023-05-16 01:59 UTC, dyzheng commented on source/module_ri/Mix_Data.hpp
> +template<typename Tdata>
```suggestion
/**
 * @brief Performs Pulay mixing of the input data.
 * @param data_in Input data to be mixed.
 * @param flag_restart Flag indicating if it is a restart.
 */
template<typename Tdata>
```

2023-05-16 01:59 UTC, dyzheng commented on source/module_ri/Mix_Data.hpp
> +template<typename Tdata>
```suggestion
/**
 * @brief Sets the Pulay mixing coefficients.
 * @tparam ChgMix Type of the charge mixing coefficient.
 * @param iter Iteration number.
 * @param chr_mix Charge mixing coefficient.
 */
template<typename Tdata>
```

2023-05-17 08:15 UTC, merged