Doc: Update the parameters about DFT+U and Electric field and dipole correction
deepmodeling/abacus-develop pull request #2506
Opened 2023-05-23 08:37 UTC by lauthirteen

Update the parameters about DFT+U and Electric field and dipole correction

2023-05-23 18:16 UTC, Satinelamp commented on docs/advanced/input_files/input-main.md
> +  - True: ABCUS will calculate plus U correction, which is especially important for correlated electron.
There is a typo of `ABCUS`

2023-05-23 18:16 UTC, Satinelamp commented on docs/advanced/input_files/input-main.md
> +  - False: ABCUS will not plus U correction.
There is a typo of `ABCUS`

2023-05-25 13:29 UTC, dyzheng requested changes

2023-05-25 13:29 UTC, dyzheng commented on docs/advanced/input_files/input-main.md
> +- **Description**:
```suggestion
- **Description**: Determines whether to calculate the plus U correction, which is especially important for correlated electrons.
```

2023-05-25 13:29 UTC, dyzheng commented on docs/advanced/input_files/input-main.md
> +  - True: calculate plus U correction, which is especially important for correlated electron.
```suggestion
  - True: Calculate plus U correction.
```

2023-05-25 13:29 UTC, dyzheng commented on docs/advanced/input_files/input-main.md
> +  - False: not plus U correction.
```suggestion
  - False: Do not calculate plus U correction.
```

2023-05-25 13:29 UTC, dyzheng commented on docs/advanced/input_files/input-main.md
> +- **Description**: $l_1,l_2,l_3,\ldots$ for atom type 1,2,3 respectively. Specify which orbits need plus U correction for each atom.
```suggestion
- **Description**: Specifies which orbits need plus U correction for each atom type ($l_1,l_2,l_3,\ldots$ for atom type 1, 2, 3, respectively).
```

2023-05-25 13:29 UTC, dyzheng commented on docs/advanced/input_files/input-main.md
> +  - -1: The plus U correction would not be calculated for this atom.
```suggestion
  - -1: The plus U correction will not be calculated for this atom.
```

2023-05-25 13:29 UTC, dyzheng commented on docs/advanced/input_files/input-main.md
> +  - 1: For p electrons orbits need plus U correction.
```suggestion
  - 1: For p-electron orbits, the plus U correction is needed.
```

2023-05-25 13:29 UTC, dyzheng commented on docs/advanced/input_files/input-main.md
> +  - 2: For d electrons orbits need plus U correction.
```suggestion
  - 2: For d-electron orbits, the plus U correction is needed.
```

2023-05-25 13:29 UTC, dyzheng commented on docs/advanced/input_files/input-main.md
> +  - 3: For f electrons orbits need plus U correction.
```suggestion
  - 3: For f-electron orbits, the plus U correction is needed.
```

2023-05-25 13:29 UTC, dyzheng commented on docs/advanced/input_files/input-main.md
> +- **Description**: Hubbard Coulomb interaction parameter U (eV) in plus U correction, which should be specified for each atom unless Yukawa potential is used.
```suggestion
- **Description**: Specifies the Hubbard Coulomb interaction parameter U (eV) in plus U correction, which should be specified for each atom unless the Yukawa potential is used.
```

2023-05-25 13:29 UTC, dyzheng commented on docs/advanced/input_files/input-main.md
> +> Note : Since we only implemented the simplified scheme by Duradev, the 'U' here is actually Ueff which is given by hubbard U minus hund J.
```suggestion
> Note: Since only the simplified scheme by Duradev is implemented, the 'U' here is actually U-effective, which is given by Hubbard U minus Hund J.
```

2023-05-25 13:29 UTC, dyzheng commented on docs/advanced/input_files/input-main.md
> +- **Description**: whether to use the local screen Coulomb potential method to calculate the values of U and J.
```suggestion
- **Description**: Determines whether to use the local screen Coulomb potential method to calculate the values of U and J.
```

2023-05-25 13:29 UTC, dyzheng commented on docs/advanced/input_files/input-main.md
> +  - True: hubbard_u does not need to be specified.
```suggestion
  - True: `hubbard_u` does not need to be specified.
```

2023-05-25 13:29 UTC, dyzheng commented on docs/advanced/input_files/input-main.md
> +  - False: hubbard_u does need to be specified.
```suggestion
  - False: `hubbard_u` does need to be specified.
```

2023-05-25 13:29 UTC, dyzheng commented on docs/advanced/input_files/input-main.md
> +- **Description**: The screen length of Yukawa potential. If left to default, we will calculate the screen length as an average of the entire system. It's better to stick to the default setting unles
```suggestion
- **Description**: The screen length of Yukawa potential. If left to default, the screen length will be calculated as an average of the entire system. It's better to stick to the default setting unless there is a very good reason.
```

2023-05-25 13:29 UTC, dyzheng commented on docs/advanced/input_files/input-main.md
> +- **Description**: The parameter controls what form of occupation matrix control we are using.
```suggestion
- **Description**: The parameter controls the form of occupation matrix control used.
```

2023-05-25 13:29 UTC, dyzheng commented on docs/advanced/input_files/input-main.md
> +  - 0: Then no occupation matrix control is performed, and the onsite density matrix will be calculated from wavefunctions in each SCF step.
```suggestion
  - 0: No occupation matrix control is performed, and the onsite density matrix will be calculated from wavefunctions in each SCF step.
```

2023-05-25 13:29 UTC, dyzheng commented on docs/advanced/input_files/input-main.md
> +  - 1: Then the first SCF step will use an initial density matrix read from a file named `initial_onsite.dm`, but for later steps, the onsite density matrix will be updated.
```suggestion
  - 1: The first SCF step will use an initial density matrix read from a file named `[initial_onsite.dm](http://initial_onsite.dm/)`, but for later steps, the onsite density matrix will be updated.
```

2023-05-26 08:37 UTC, dyzheng approved these changes

2023-05-26 08:37 UTC, merged