Feature: add the output of E_KS(sig->0)
deepmodeling/abacus-develop pull request #2571
Opened 2023-05-31 02:37 UTC by Chentao168

Add the output of E_KS(sig->0), which is the same as energy(sigma->0) in the VASP.
![9140e56b-762d-4544-9391-704d45eaa67a](https://github.com/deepmodeling/abacus-develop/assets/76426373/39437c3b-3a20-4c1a-8495-794e23f465f1)
![image](https://github.com/deepmodeling/abacus-develop/assets/76426373/646b9e73-8fc8-4aae-af1d-b0b271ce09e5)

2023-05-31 03:02 UTC, hongriTianqi requested changes

2023-05-31 03:02 UTC, hongriTianqi commented on source/module_elecstate/elecstate_print.cpp
> +        this->print_format("E_entro(-TS)", this->f_en.demet); // mohan add 2011-12-02
E_entro is more unclear than E_entropy. Is there any special reason for this change of naming?

2023-05-31 05:35 UTC, wenfei-li commented
how does the content of the pr relate to the title? I only saw change in E_entropy not E_KS(sig->0)

2023-05-31 05:45 UTC, hongriTianqi requested changes

2023-05-31 05:45 UTC, hongriTianqi commented on source/module_elecstate/fp_energy.cpp
> +    std::cout << " entropy(-TS)=" << demet << std::endl;
Please add a unit test for this function.

2023-06-01 02:30 UTC, hongriTianqi requested changes

2023-06-01 02:30 UTC, hongriTianqi commented on source/module_elecstate/test/elecstate_fp_energy_test.cpp
> +    EXPECT_THAT(output, testing::HasSubstr("entropy(-TS)="));
It is confusing to use entropy at one place, but entro at another place. Could you please give explanations about their difference in the code?

2023-06-01 14:33 UTC, hongriTianqi requested changes
Add necessary explanation for your pr

2023-06-02 07:40 UTC, dyzheng commented on source/module_elecstate/elecstate_print.cpp
> +        this->print_format("E_KS(sig->0)", this->f_en.etot - this->f_en.demet/(2+n_order));
@wenfei-li this line add E(sigma->0), but @Chentao168 can you add some annotation for this line? what is the related formula?

2023-06-02 22:48 UTC, hongriTianqi requested changes

2023-06-02 22:48 UTC, hongriTianqi commented on source/module_elecstate/elecstate_print.cpp
>          GlobalV::ofs_running << "\n " << std::setw(12) << "Energy" << std::setw(30) << "Rydberg" << std::setw(30)
please align all the energy terms.

2023-06-03 04:30 UTC, hongriTianqi approved these changes

2023-06-04 07:55 UTC, dyzheng approved these changes

2023-06-04 08:29 UTC, merged