Test: UnitTest for module_tddft
deepmodeling/abacus-develop pull request #2580
Opened 2023-06-01 06:53 UTC by lyb9812

Add unit tests for module_tddft.

2023-06-01 06:56 UTC, hongriTianqi requested changes

2023-06-01 06:56 UTC, hongriTianqi commented on source/module_base/blacs_connector.h
> +    void Cblacs_gridinit(int* icontxt, char* layout, int nprow, int npcol);
Please add unit tests for these newly added blas connectors, too. Thanks!

2023-06-01 06:59 UTC, hongriTianqi requested changes

2023-06-01 06:59 UTC, hongriTianqi commented on source/module_hamilt_lcao/module_tddft/test/CMakeLists.txt
> +  SOURCES tddft_test.cpp upsi_test1.cpp upsi_test2.cpp upsi_test3.cpp propagator_test1.cpp propagator_test2.cpp propagator_test3.cpp middle_hamilt_test.cpp norm_psi_test.cpp bandenergy_test.cpp ../up
I suggest to add each tests separately with a specific namely to facilitate checking of the corresponding functionalities.

2023-06-04 03:31 UTC, hongriTianqi requested changes

2023-06-04 03:31 UTC, hongriTianqi commented on source/module_hamilt_lcao/module_tddft/test/CMakeLists.txt
> +  TARGET middle_hamilt_test
It is suggested to add prefix "tddft" for all the tests' name.

2023-06-05 02:03 UTC, Qianruipku commented
The CI for testing now takes a total of 40 minutes. What is the reason that the test takes 5 more minutes than before?

2023-06-05 03:20 UTC, hongriTianqi commented
> The CI for testing now takes a total of 40 minutes. What is the reason that the test takes 5 more minutes than before?

More specifically, the case tests 5 more minutes than before (1359 vs 1054 seconds).

2023-06-07 02:57 UTC, mohanchen approved these changes

2023-06-07 05:46 UTC, hongriTianqi requested changes
Can you please analyze the reason why case tests take 5 minutes more in this PR? @lyb9812

2023-06-07 05:51 UTC, hongriTianqi commented
> Can you please analyze the reason why case tests take 5 minutes more in this PR?

In addition, multiple case tests deliver warnings with large derivation from the original results. This is unacceptable:

<img width="271" alt="截屏2023-06-07 13 50 00" src="https://github.com/deepmodeling/abacus-develop/assets/18049272/5e6cf05f-f39d-4739-a236-6e5023054947">

2023-06-07 06:11 UTC, hongriTianqi commented
> > Can you please analyze the reason why case tests take 5 minutes more in this PR?
> 
> In addition, multiple case tests deliver warnings with large derivation from the original results. This is unacceptable:
> 
> <img alt="截屏2023-06-07 13 52 49" width="778" src="https://user-images.githubusercontent.com/18049272/243925810-5aa516e6-dffd-4f48-8d1c-b13e5a37d9cd.png">
> @mohanchen
> 
> <img alt="截屏2023-06-07 13 50 00" width="271" src="https://user-images.githubusercontent.com/18049272/243925428-5e6cf05f-f39d-4739-a236-6e5023054947.png">

This ISSUE is induced by my own PR #2477. I will take care of this issue.

2023-06-07 06:11 UTC, hongriTianqi approved these changes

2023-06-07 06:16 UTC, hongriTianqi requested changes
Wait, there are more warnings in this PR than PR #2477. Please check if this is related to this PR.

2023-06-07 06:25 UTC, lyb9812 commented
> Can you please analyze the reason why case tests take 5 minutes more in this PR? @lyb9812

The total time of tests change from 34m to 40m since PR#2477.

2023-06-07 06:30 UTC, lyb9812 commented
> Wait, there are more warnings in this PR than PR #2477. Please check if this is related to this PR.
> 
> For comparison, the warnings appeared in the following cases in PR #2477.
> 
> <img alt="截屏2023-06-07 14 15 27" width="546" src="https://user-images.githubusercontent.com/18049272/243931634-491fe741-fe8f-4bae-8e8c-76ed267210f2.png">

The warnings are the same as PR #2604 (the last received PR). So it is not introduced by this PR. It seems start from PR #2527 .

2023-06-07 06:58 UTC, hongriTianqi commented
can you please check the two test cases of 601, which are related to TDDFT code. Can you please solve the warnnings in these two case tests? Thanks! @lyb9812

2023-06-07 07:02 UTC, hongriTianqi commented
> > Wait, there are more warnings in this PR than PR #2477. Please check if this is related to this PR.
> > For comparison, the warnings appeared in the following cases in PR #2477.
> > <img alt="截屏2023-06-07 14 15 27" width="546" src="https://user-images.githubusercontent.com/18049272/243931634-491fe741-fe8f-4bae-8e8c-76ed267210f2.png">
> 
> The warnings are the same as PR #2604 (the last received PR). So it is not introduced by this PR. It seems start from PR #2527 .

The warnings do not start from PR #2527, I am still searching for it ....

2023-06-07 07:03 UTC, hongriTianqi commented
This issue is not induced by PR #2477, I am still searching for it ...

2023-06-07 07:27 UTC, hongriTianqi commented
> The CI for testing now takes a total of 40 minutes. What is the reason that the test takes 5 more minutes than before?

5 more minutes are taken by EXX case tests, which were introduced in PR #2478. @lyb9812 @Qianruipku

2023-06-07 11:40 UTC, lyb9812 commented
> can you please check the two test cases of 601, which are related to TDDFT code. Can you please solve the warnnings in these two case tests? Thanks! @lyb9812
> 
> <img alt="tt" width="587" src="https://user-images.githubusercontent.com/18049272/243949282-49ecce46-8585-495f-9a38-3be4104b6c4f.PNG">



> can you please check the two test cases of 601, which are related to TDDFT code. Can you please solve the warnnings in these two case tests? Thanks! @lyb9812
> 
> <img alt="tt" width="587" src="https://user-images.githubusercontent.com/18049272/243949282-49ecce46-8585-495f-9a38-3be4104b6c4f.PNG">

There are no changes related to tddft in PR #2503 . The warnings in these two cases may be due to the random phase of wavefunction. I will confirm it after I complete function of restart

2023-06-07 12:34 UTC, hongriTianqi approved these changes

2023-06-08 07:18 UTC, dyzheng approved these changes

2023-06-08 07:19 UTC, merged