Refactor(input model): create the input
deepmodeling/abacus-develop pull request #2646
Opened 2023-06-16 04:35 UTC by grysgreat

rebuild class and function. This has no effect on the current code.
 Refactor #2549

2023-06-16 04:37 UTC, grysgreat commented
Refact the input model. - Gu Hongyaoxing

2023-06-19 01:10 UTC, mohanchen requested changes

2023-06-19 01:10 UTC, mohanchen commented on source/module_io/parameter_pool.h
Use English notes.

2023-06-19 01:10 UTC, mohanchen commented on source/module_io/parameter_pool.h
> +         * @param t ��������ö��ֵ
Use English for all of the notes in ABACUS

2023-06-20 02:46 UTC, hongriTianqi requested changes

2023-06-20 02:46 UTC, hongriTianqi commented on source/module_io/parameter_pool.cpp
> +bool input_parameters_get(const std::string& fn)
Please add unit tests for all the newly added functions.

2023-06-20 02:46 UTC, hongriTianqi commented on source/module_io/parameter_pool.cpp
> +void strtolower(char* sa, char* sb)
Please write the new functions inside the namespace ModuleIO

2023-06-20 02:47 UTC, hongriTianqi requested changes
Please remove the empty git file

2023-06-20 09:46 UTC, closed without merging