Feature : new implementation of DFT+U
deepmodeling/abacus-develop pull request #2761
Opened 2023-07-27 08:22 UTC by wenfei-li

For more details, check the comment in LCAO_dftu_new.h

2023-08-03 10:52 UTC, wenfei-li commented
This functionality is unfinished. There is a problem related to passing kv.isk all the way down into folding_fixedH. It can be solved, but is rather cumbersome. In the meantime I'm also waiting for the completion of a test workflow. As a result, I'll leave it as is for now and resume on this project later.

2023-08-07 06:22 UTC, wenfei-li commented
I've done SCF for multi-k (so no gamma point, no force & stress); the results seems to be reasonable. I will wait for the completion of test workflow and continue on this project only when the new implementation is tested to be useful.

2023-08-08 05:23 UTC, wenfei-li commented
I turned off coverage for this module because this functionality is not intended to be used as an official functionality but rather something to make experiments on. Another option would be to not merge this pr and use my dftu branch for the experiments. I'll wait for further discussion on this problem.

2023-08-09 21:46 UTC, hongriTianqi commented
@wenfei-li @baixiaokuang Sorry that I cannot agree to merge this PR directly into the develop branch by turning off coverage and without unit tests. The reason is simple, without unit tests, one cannot make sure that the new feature won't be breaker by future PRs, and cannot make sure it won't break existing functions of the code.

2023-08-09 21:47 UTC, hongriTianqi requested changes

2023-08-09 21:47 UTC, hongriTianqi commented on source/module_hamilt_lcao/module_dftu_new/LCAO_dftu_new.cpp
> +LCAO_DftU_New::LCAO_DftU_New()
Please add unit tests for the new module. Thanks.

2023-08-14 05:06 UTC, wenfei-li commented
alright then we'll use my dftu branch for testing purpose

2023-10-24 05:10 UTC, dyzheng commented
I will test the dftu branch, set this PR to draft.

2024-01-15 10:26 UTC, closed without merging