Refactor: Implement read and write dmk with a UnitTest
deepmodeling/abacus-develop pull request #2809
Opened 2023-08-09 02:51 UTC by WHUweiqingzhou

Implement #2801

Change List:
1. add a new subdirectory `module_elecstate/module_dm/` to store density matrix source files
2. In `module_elecstate/module_dm/`, implement two new function to read and write dmk `read_dmk()` and `write_dmk()`
3. add corresponding UnitTest of `read_dmk()` and `write_dmk()`

2023-08-09 04:33 UTC, hongriTianqi requested changes

2023-08-09 04:33 UTC, hongriTianqi commented on source/module_elecstate/module_dm/dmk_io.cpp
> +void ModuleIO::write_dmk(
I suggest to change the namespace from ModuleIO to elecstate

2023-08-09 04:36 UTC, hongriTianqi approved these changes

2023-08-09 04:36 UTC, hongriTianqi commented on source/module_elecstate/module_dm/test/CMakeLists.txt
> +  TARGET read_dm_gamma
Please rename the test

2023-08-09 04:42 UTC, hongriTianqi requested changes

2023-08-09 04:42 UTC, hongriTianqi commented on source/module_elecstate/module_dm/test/test_readdmgamma.cpp
> +TEST_F(DMIOTest,Read)
This is a repeat of unit test in module_io, and I suggest not to add it here.

2023-08-09 08:33 UTC, hongriTianqi commented on source/module_elecstate/module_dm/dmk_io.h
> +	void write_dmk(const K_Vectors& kv,const int& ik,const std::string &fn, const int &precision,std::vector<ModuleBase::ComplexMatrix> &dm_k);
Please add comments on header file

2023-08-10 01:53 UTC, hongriTianqi requested changes

2023-08-10 01:53 UTC, hongriTianqi commented on source/module_elecstate/module_dm/dmk_io.cpp
> +    for(int i=0; i<GlobalV::NLOCAL; ++i)
GlobalV::NLOCAL is suggested to be removed from beginning.

2023-08-10 01:58 UTC, hongriTianqi requested changes

2023-08-10 01:58 UTC, hongriTianqi commented on source/module_elecstate/module_dm/dmk_io.cpp
> +    if(GlobalV::MY_RANK==0)
GlobalV::MY_RANK is not set in the unit test, which might cause errors.

2023-08-10 03:04 UTC, dyzheng approved these changes

2023-08-10 03:07 UTC, dyzheng commented on source/module_elecstate/module_dm/test/CMakeLists.txt
> +  ${ABACUS_SOURCE_DIR}/module_cell/klist.cpp
In my opinion, add a mock of klist.h for functions you need is a better solution.

2023-08-11 06:13 UTC, dyzheng approved these changes

2023-08-11 06:39 UTC, hongriTianqi approved these changes

2023-08-11 07:03 UTC, merged