Feature : added paw_cell_libpaw and test
deepmodeling/abacus-develop pull request #2815
Opened 2023-08-09 14:54 UTC by wenfei-li

2023-08-10 02:00 UTC, hongriTianqi requested changes

2023-08-10 02:00 UTC, hongriTianqi commented on source/module_cell/module_paw/test/test_paw3.cpp
> +
Please add comments on the tested functions and a brief intrucdution of the functionality.

2023-08-14 06:27 UTC, wenfei-li commented on source/module_cell/module_paw/test/test_paw3.cpp
> +
I've added explanations of unit tests

2023-08-14 08:43 UTC, hongriTianqi approved these changes

2023-08-14 08:44 UTC, merged