Feature: add abacus toolchain
deepmodeling/abacus-develop pull request #2857
Opened 2023-08-22 14:04 UTC by QuantumMisaka

Toolchain scripts for quickly and properly compile and install dependencies of ABACUS including:

- gnu-toolchain
- - `gcc` (always in system)
- - `openblas`
- - `openmpi` or `mpich`
- - `scalapack`, `fftw`, `elpa` , `libxc`
- - `cereal`, `libnpy`, `libtorch`
- intel-toolchain (likely)

Version 2023.1 inspired by cp2k-toolchain.
Still need more test and improvement, but can have good usage.

The toolchain directory is designed to be in the path of ABACUS itself.

2023-08-22 14:39 UTC, dyzheng commented
There are too much new files in this PR. Please check your changes.

2023-08-22 22:48 UTC, QuantumMisaka commented
@dyzheng  Got it, much new file mainly in `libs/cereal` and `libs/libnpy`, now fix it.

2023-08-23 02:36 UTC, caic99 requested changes
@QuantumMisaka 
Thanks for your contribution! I believe these script will help users a lot.

However, please remove the release packages under libs. Doing so is an action of  redistribution and integration of those software packages. This is strongly not recommended because it might introduce incompatibility on licenses. (And you did not include the license files of those packages.)

It is OK to download them in your script. If you think integrating them in ABACUS repo is necessary, please use git submodule.
Thanks!

2023-08-23 02:39 UTC, caic99 commented
@QuantumMisaka And, if you wish, you can add docs or links to the toolchain under corresponding parts of `abacus-develop/docs` in online docs to promote it.

2023-08-23 02:59 UTC, QuantumMisaka commented
@caic99 I also want to remove the libraries in `libs` and use toolchain to install it, I'm trying to do this but It's hard to choose the way to introduce the installation (by `git clone` or `wget` from the release, and neither way can bypass `github.com`, which will bring the HTTP problem). So I highly want to solve this with your help.

Also, the `docs` file is in plan. I'm wandering if the README file can be directly copy to `docs` directory, 

Thanks !

2023-08-23 03:12 UTC, caic99 commented
> @caic99 I also want to remove the libraries in `libs` and use toolchain to install it, I'm trying to do this but It's hard to choose the way to introduce the installation (by `git clone` or `wget` from the release, and neither way can bypass `github.com`, which will bring the HTTP problem). So I highly want to solve this with your help.

In principle it is the user's responsibiliy guaranteeing the internet connection. However, considering the actual situations, maybe you can provide some mirror sites of GitHub (e.g. fastgit) in place of the fixed base domain of github.com . Using [gitee mirroring service](https://gitee.com/mirrors) is a more secure way. 

> Also, the `docs` file is in plan. I'm wandering if the README file can be directly copy to `docs` directory

Please choose a good place for it to maintain the structure. Maybe under [quick_start](https://github.com/deepmodeling/abacus-develop/tree/develop/docs/quick_start) folder, and add an introduction for it at [easy_install.md](https://github.com/deepmodeling/abacus-develop/blob/develop/docs/quick_start/easy_install.md)? What do you think?

2023-08-23 10:54 UTC, wenfei-li commented on toolchain/libs/cereal-1.3.2.tar.gz
I do not think we should include tar.gz file in ABACUS repository

2023-08-23 11:14 UTC, QuantumMisaka commented on toolchain/libs/cereal-1.3.2.tar.gz
It's surely not, I'm trying to add `cereal` and `libnpy` in toolchain installation

2023-08-23 14:19 UTC, QuantumMisaka commented on toolchain/libs/cereal-1.3.2.tar.gz
Fixed it

2023-08-23 14:53 UTC, caic99 commented on toolchain/README.md
> +- [ ] A better mirror station for all packages, espeacially for CEREAL and LIBNPY.
```suggestion
- [ ] A better mirror station for all packages, especially for CEREAL and LIBNPY.
```

2023-08-31 15:27 UTC, QuantumMisaka commented
@caic99 A problem in my try for introducing `LibRI` in `dep` to toolchain installation by using intel-icc-toolchain
```bash
In file included from /lustre/home/2201110432/apps/abacus/icc-mkl/deps/LibRI/include/RI/global/Tensor.h(8),
                 from /lustre/home/2201110432/apps/abacus/icc-mkl/source/module_hamilt_lcao/hamilt_lcaodft/LCAO_matrix.h(13),
                 from /lustre/home/2201110432/apps/abacus/icc-mkl/source/module_io/restart.h(6),
                 from /lustre/home/2201110432/apps/abacus/icc-mkl/source/module_hamilt_pw/hamilt_pwdft/global.h(8),
                 from /lustre/home/2201110432/apps/abacus/icc-mkl/source/module_cell/klist.cpp(1):
/lustre/home/2201110432/apps/abacus/icc-mkl/deps/LibRI/include/RI/global/Shared_Vector.h(8): catastrophic error: cannot open source file "cereal/cereal.hpp"
  #include <cereal/cereal.hpp>

compilation aborted for /lustre/home/2201110432/apps/abacus/icc-mkl/source/module_cell/klist.cpp (code 4)
gmake[2]: *** [source/module_cell/CMakeFiles/cell.dir/build.make:244: source/module_cell/CMakeFiles/cell.dir/klist.cpp.o] Error 4
```
What's the best way for `LibRI` to find `CEREAL` ?

2023-09-01 02:22 UTC, caic99 commented
> @caic99 A problem in my try for introducing `LibRI` in `dep` to toolchain installation by using intel-icc-toolchain
> 
> ```shell
> In file included from /lustre/home/2201110432/apps/abacus/icc-mkl/deps/LibRI/include/RI/global/Tensor.h(8),
>                  from /lustre/home/2201110432/apps/abacus/icc-mkl/source/module_hamilt_lcao/hamilt_lcaodft/LCAO_matrix.h(13),
>                  from /lustre/home/2201110432/apps/abacus/icc-mkl/source/module_io/restart.h(6),
>                  from /lustre/home/2201110432/apps/abacus/icc-mkl/source/module_hamilt_pw/hamilt_pwdft/global.h(8),
>                  from /lustre/home/2201110432/apps/abacus/icc-mkl/source/module_cell/klist.cpp(1):
> /lustre/home/2201110432/apps/abacus/icc-mkl/deps/LibRI/include/RI/global/Shared_Vector.h(8): catastrophic error: cannot open source file "cereal/cereal.hpp"
>   #include <cereal/cereal.hpp>
> 
> compilation aborted for /lustre/home/2201110432/apps/abacus/icc-mkl/source/module_cell/klist.cpp (code 4)
> gmake[2]: *** [source/module_cell/CMakeFiles/cell.dir/build.make:244: source/module_cell/CMakeFiles/cell.dir/klist.cpp.o] Error 4
> ```
> 
> What's the best way for `LibRI` to find `CEREAL` ?

Hi @QuantumMisaka ,
Please check if `LibRI` has `CEREAL` for its git submodule. If not so, you can add `CEREAL` as an submodule in your toolchain.

2023-09-01 02:26 UTC, caic99 commented
> Hi @QuantumMisaka , Please check if `LibRI` has `CEREAL` for its git submodule. If not so, you can add `CEREAL` as an submodule in your toolchain.

@QuantumMisaka Update: Please check in your terminal if `cereal/cereal.hpp` can be opened in editor like `vim`. If the file is not present, the warning message would be `fatal error: xxx.h: No such file or directory`, but not `catastrophic error: cannot open source file`. The latter means the file presents, but the compiler can not open it. Please check file access permission.

2023-09-01 03:01 UTC, QuantumMisaka commented
> @QuantumMisaka Update: Please check in your terminal if `cereal/cereal.hpp` can be opened in editor like `vim`. If the file is not present, the warning message would be `fatal error: xxx.h: No such file or directory`, but not `catastrophic error: cannot open source file`. The latter means the file presents, but the compiler can not open it. Please check file access permission.

- The permission of `cereal.hpp` is 644, which can be open by `vim`, 
- The problem still exists after change permission of `cereal.hpp` to `777`
- The problem will be fixed if `export CPATH="cereal/include":$CPATH

2023-09-01 05:55 UTC, caic99 approved these changes

2023-09-01 05:55 UTC, merged