Test: add precision tests for sphbesj
deepmodeling/abacus-develop pull request #2958
Opened 2023-09-15 08:58 UTC by jieli-matrix

1. `sphbesj` passed the precision tests where the threshold is set to `1e-12`.
2. `Spherical_Bessel` failed to pass the tests (especially when `l = 4` the error rises to `1e-6` ) thus `TEST_F(Sphbes, SeriesAndRecurrence)` is removed.

2023-09-15 09:18 UTC, jinzx10 requested changes
It seems the current test grid is uniform. Is it possible to add some extra-fine sample points near 0, like 0.01, 0.001, 0.0001, 0.00001...? (no necessarily a log grid with base 10)

2023-09-18 09:47 UTC, jieli-matrix commented
I have added data points around 0 with a data range that spans from `1e-7` to `1e-2` in a log grid with base 2, and all tests have passed. cc: @jinzx10

2023-09-19 16:01 UTC, jinzx10 commented
It seems sphbes.m still has some problems:
1. xm on line 9 is undefined;
2. sphbes(0, 0) is not computed correctly;
3. even if nu and x have the same shape, if x contains some 0, arguments passed to besselj would have different sizes, thereby causing an error;
4. js is not preallocated; "js(~x) = 0" would produce an array of size 0.
5. if I remember correctly, nzind = find(x) would produce a column vector. If nu & x are matrices, the arguments passed to besselj would have mismatched sizes since x(nzind) would be a column vector.

PS: if you feel writing a robust sphbes function is tedious and unnecessary, maybe removing those matlab/octave scripts is just fine.

2023-09-20 09:41 UTC, jinzx10 approved these changes

2023-09-20 09:41 UTC, jinzx10 approved these changes

2023-09-21 07:39 UTC, dyzheng approved these changes

2023-09-21 07:39 UTC, merged