add re-initialization after vcrelax
deepmodeling/abacus-develop pull request #3031
Opened 2023-09-26 11:47 UTC by kirk0830

codes and annotations

2023-09-27 09:20 UTC, kirk0830 commented
![image](https://github.com/deepmodeling/abacus-develop/assets/67682086/bfdf7ff0-ca9f-4908-9068-a001b3875069)

2023-09-27 10:01 UTC, hongriTianqi approved these changes

2023-09-28 00:52 UTC, hongriTianqi requested changes

2023-09-28 00:52 UTC, hongriTianqi commented on source/module_psi/test/psi_initializer_integrated_test.cpp
> +    error = std::system("cp ../../../../source/module_psi/test/support/atomic_random_new ./INPUT");
We can use cmake install to find support files

2023-09-28 00:53 UTC, hongriTianqi commented on source/module_psi/test/psi_initializer_integrated_test.cpp
> +    error = std::system("../../../abacus");
Is this good practice to call abacus in unit test?

2023-09-28 06:03 UTC, hongriTianqi requested changes

2023-09-28 06:03 UTC, hongriTianqi commented on source/module_psi/test/psi_initializer_integrated_test.cpp
>      error = std::system("../../../abacus");
Please avoid using the "abacus" executable in unit test.

2023-09-30 07:31 UTC, hongriTianqi commented on docs/advanced/input_files/input-main.md
> +  - atomic: from atomic pseudo wave functions. If they are not enough, other wave functions are initialized with random numbers.
It is better not to repeat information on "atomic" and "atom+random" choices?

2023-09-30 07:32 UTC, hongriTianqi commented on docs/advanced/input_files/input-main.md
> +  - nao: from numerical atomic orbitals. If they are not enough, other wave functions are initialized with random numbers.
- nao: from numerical atomic orbitals. If they are not enough, other wave functions are initialized with random numbers. Available only if `psi_initializer` is set to 1.

2023-09-30 07:33 UTC, hongriTianqi commented on docs/advanced/input_files/input-main.md
> +  - nao+random: add small random numbers on numerical atomic orbitals
```suggestion
  - nao+random: add small random numbers on numerical atomic orbitals. Available only if `psi_initializer` is set to 1.

2023-10-03 23:55 UTC, hongriTianqi approved these changes

2023-10-04 00:03 UTC, merged