Build: update Dockerfile.gnu with mpifort for paw test case
deepmodeling/abacus-develop pull request #3079
Opened 2023-10-19 02:23 UTC by hongriTianqi

2023-10-19 03:06 UTC, hongriTianqi commented
@caic99 The change of docker file seems not solve the problem. How can we update the docker image for running the CI tests?

2023-10-19 04:07 UTC, caic99 requested changes

2023-10-19 04:07 UTC, caic99 commented on Dockerfile.gnu
> +RUN apt-get install -y libmpich-dev mpich
Please put `apt-get` commands all together.

2023-10-19 04:08 UTC, caic99 commented
> @caic99 The change of docker file seems can not solve the problem. How can we update the docker image for running the CI tests?

@hongriTianqi Once this PR is merged, the new image will be built and applies to the following tests.

2023-10-19 05:49 UTC, caic99 approved these changes

2023-10-19 05:49 UTC, dyzheng approved these changes
This PR seems can solve the CI test error for PAW cases.
Only GNU image has been fixed in this PR.

2023-10-19 05:50 UTC, dyzheng commented
Can you link the PR which caused this problem?

2023-10-19 05:57 UTC, merged

2023-10-20 04:11 UTC, caic99 commented
@hongriTianqi I would suggest reverting this PR since it does not actually solves the problem which has been fixed by @wenfei-li .