Fix: symmetrize charge density in reciprocal space in any case
deepmodeling/abacus-develop pull request #3081
Opened 2023-10-19 09:41 UTC by maki49

fix #3070  #2608

2023-10-19 14:16 UTC, dyzheng approved these changes
I agree with this Fix code, will the function "psymm" not be used any more due to the new symmetry algorithm?

2023-10-19 14:55 UTC, maki49 commented
> I agree with this Fix code, will the function "psymm" not be used any more due to the new symmetry algorithm?

Currently yes, but I think it's better to keep it in case of future usage. 
Should I comment out the implementation too for unit test coverage?

2023-10-20 02:06 UTC, pxlxingliang commented
Hi, @maki49 please add an integrate test for symmetry. Suggest using the structure in issue #3070 and using the results of symmetry = 0 as the reference, and please also modify the INPUT to reduce the running time (preferably around 10 seconds)

2023-10-20 02:27 UTC, pxlxingliang requested changes
Hi, @maki49 please add an integrate test for symmetry. Suggest using the structure in issue https://github.com/deepmodeling/abacus-develop/issues/3070 and using the results of symmetry = 0 as the reference, and please also modify the INPUT to reduce the running time (preferably around 10 seconds)

2023-10-20 04:34 UTC, hongriTianqi requested changes
The number of warnings in CI test increased from 56 to 87. Please treat the CI case reference if needed.

2023-10-20 05:31 UTC, maki49 commented
> The number of warnings in CI test increased from 56 to 87. Please treat the CI case reference if needed.

To avoid warnings is conflict with the demand of @pxlxingliang : if results with symmetry=0 are used as the reference to run test cases with symmetry=1, the warnings will be inevitable unless loosing the threshold.

2023-10-20 06:10 UTC, hongriTianqi commented
> > The number of warnings in CI test increased from 56 to 87. Please treat the CI case reference if needed.
> 
> To avoid warnings will be conflict with the demand of @pxlxingliang : if results with symmetry=0 are used as the reference to run test cases with symmetry=1, the warnings will be inevitable unless loosing the threshold.

Sorry, I don't understand why the warnings will be inevitable.

2023-10-20 06:14 UTC, maki49 commented
> Sorry, I don't understand why the warnings will be inevitable.

The magnitude of the energy difference between symmetry=0 and symmetry=1 could be around 1e-3 Ry. See some results I've tested before: https://xmywuqhxb0.feishu.cn/docx/MAAadv569onfU0xtbc5cEFwjnRh?from=from_copylink

2023-10-20 06:52 UTC, dyzheng commented
> > The number of warnings in CI test increased from 56 to 87. Please treat the CI case reference if needed.
> 
> To avoid warnings will be conflict with the demand of @pxlxingliang : if results with symmetry=0 are used as the reference to run test cases with symmetry=1, the warnings will be inevitable unless loosing the threshold.

I suggest to change reference from "symmetry=0" to "symmetry=1" in these cases. 
I have tested QE for low ecutrho, there is inevitable error between symmetry on and off.

2023-10-23 00:53 UTC, maki49 commented
I wonder why `902_OF_KE_WT` timed out on CI... 
I cannot reproduce it on both my workstation and bohrium.

2023-10-23 01:56 UTC, hongriTianqi commented
> I wonder why `902_OF_KE_WT` timed out on CI...
> I failed to reproduce it on both my workstation and Bohrium, complied by both Intel and GNU.

It's because the total time limit for case tests are 1500 seconds.

2023-10-23 03:07 UTC, dyzheng approved these changes

2023-10-23 06:00 UTC, dyzheng commented
> I wonder why `902_OF_KE_WT` timed out on CI... I failed to reproduce it on both my workstation and Bohrium, complied by both Intel and GNU.

Some cases (such as 204_NO_KP_AFM : 110 s vs 17 s) used much more time than before.

2023-10-23 06:26 UTC, dyzheng requested changes
Please fix the bugs in CI

2023-10-23 16:58 UTC, maki49 commented
> Please fix the bugs in CI

Is it possible that it's a convergence to a stabler state (with lower energy and smaller stress) rather than a bug?

2023-10-24 09:08 UTC, dyzheng commented
> Is it possible that it's a convergence to a more stable state (with lower energy and smaller stress) rather than a bug? (I'm not sure, maybe more tests are needed...)

I don't agree your point, the critical point is this case is anti-ferromagnetic material, I tested "ecutwfc 100" and KPT: 6 6 6 for both "nspin 1" and "nspin 2".
Results of "nspin 1" are same among symmetry=-1, 0, and 1.
But results of "nspin 2" are same between symmetry = -1, 0, and different with symmetry = 1.

You can test by yourself~

2023-10-24 14:19 UTC, maki49 commented
> I don't agree your point, the critical point is this case is anti-ferromagnetic material, I tested "ecutwfc 100" and KPT: 6 6 6 for both "nspin 1" and "nspin 2". Results of "nspin 1" are same among symmetry=-1, 0, and 1. But results of "nspin 2" are same between symmetry = -1, 0, and different with symmetry = 1.
> 
> You can test by yourself~

You're right. This problem arises from the loop of primitive cells in supercell during reciprocal-space charge density symmetrization. The primitive cell analysis doesn't consider atom magmoms, which gives more primitive cells than the right answer.
- Current fix: if not all the atoms in its type has the same magmom, do not traverse primitive cells in `rhog_symmetry`. (This way may lead to a possible incomplete symmetrization due to not exploiting all the primitive-cell-translational symmetry, but it can give the right result.)
- Perfect solution In the future: [spglib](https://github.com/spglib/spglib) can be used as an option to analyze magnetic space group.

2023-10-26 03:11 UTC, dyzheng approved these changes

2023-10-26 03:13 UTC, pxlxingliang approved these changes

2023-10-26 03:16 UTC, hongriTianqi approved these changes

2023-10-26 03:23 UTC, dyzheng commented
Thanks for your excelIent work for fixing symmetry bugs! 
I suggest to merge this PR as soon as possible.
I hope any volunteer who will be interested to add more unit tests to cover every case of symmetry in the future.

2023-10-26 03:23 UTC, merged