In integrate test add force threshold of 0.0001 and stress threhold 0.001…
deepmodeling/abacus-develop pull request #3088
Opened 2023-10-22 15:25 UTC by Zhuxuegang2022

…to made less warning output

### Reminder
- [x] Have you linked an issue with this pull request?
- [ ] Have you noticed possible changes of behavior below or in the linked issue?
- [ ] Have you explained the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi? (ignore if not applicable)

### Linked Issue
Fix #2844 

### What's changed?
In integrate test add force threshold of 0.0001 and stress threhold of 0.001. this change will let less "warning" to output.

2023-10-23 01:55 UTC, hongriTianqi commented
Please check to bash script, there might be an error to cause the warning in the picture:
<img width="946" alt="截屏2023-10-23 09 53 22" src="https://github.com/deepmodeling/abacus-develop/assets/18049272/0ca1dba1-19e6-443d-ba92-bcd4a6bc93e5">

2023-10-23 02:18 UTC, Zhuxuegang2022 commented on tests/integrate/Autotest.sh
>  			if [ $(echo "sqrt($deviation*$deviation) < $threshold"|bc) = 0 ]; then
if [ $(echo "sqrt($deviation*$deviation) < $threshold"|bc) = 0  ]; then

2023-10-23 02:42 UTC, caic99 commented on tests/integrate/Autotest.sh
> +				if [ $key == "totalforceref" -o $key == "totalstressref"]; then
```suggestion
				if [ $key == "totalforceref" -o $key == "totalstressref" ]; then
```

@Zhuxuegang2022 Actually this if statement is not necessary by "if... elif ... else".

2023-10-23 03:32 UTC, caic99 commented
@Zhuxuegang2022 #2552 may be solved by remove all warnings in a new PR after merging this one.

2023-10-23 06:32 UTC, dyzheng requested changes
please format your code, tabs should be replace by spaces.

2023-10-24 05:01 UTC, dyzheng approved these changes
I agree to set force_threshold and stress_threshold to broaden criterion, because results of different compilers or machines may have small digital errors.

2023-10-24 06:24 UTC, merged