Add performace test of sphbes functions.
deepmodeling/abacus-develop pull request #3492
Opened 2024-01-15 07:28 UTC by grysgreat

Using google benchmark as the background, a series of performance test code was added（https://github.com/google/benchmark.git）

### Linked Issue
Fix #3491

### What's changed?
- Added compilation options for performance test code
- Performance test code for the sphbes function has been added to module base

### Any changes of core modules? (ignore if not applicable)
- none

2024-01-16 03:47 UTC, caic99 requested changes

2024-01-16 03:47 UTC, caic99 commented on CMakeLists.txt
> +IF (ENABLE_GOOGLEBENCH)
Since googlebench relies on testing mechanism and googletest toolkit, please set `ENABLE_GOOGLEBENCH` as affiliated to `BUILD_TESTING`.

2024-01-16 08:45 UTC, jieli-matrix commented
Since we have added performance tests where the results will show the time costs of functions by running random times, maybe we can remove `timer.h` from module base. cc: @mohanchen

2024-01-18 03:31 UTC, jieli-matrix commented
Closed this PR since I will take on the work in PR #3511. cc: @grysgreat @caic99

2024-01-18 03:31 UTC, closed without merging