Test: Configure performance tests for math libraries
deepmodeling/abacus-develop pull request #3511
Opened 2024-01-18 03:27 UTC by jieli-matrix

### Description

Configure performance tests for math libraries by using [google benchmark](https://github.com/google/benchmark.git) as I mentioned in #3491.

ToDo:
- [x] Configure benchmark in cmake.
- [ ] Configure workflows.
- [ ] Add performance tests for `math_sphbes`.

2024-01-18 04:05 UTC, caic99 requested changes

2024-01-18 04:05 UTC, caic99 commented on CMakeLists.txt
> +  option(BUILD_TESTING "GoogleBenchmark relies on google googletest toolkit." ON)
Please put this option ahead of the setup of googletest.

2024-01-18 04:05 UTC, caic99 commented on CMakeLists.txt
> +  find_package(benchmark HINTS /usr/local/lib/ ${BENCHMARK_DIR})
```suggestion
  find_package(benchmark HINTS ${BENCHMARK_DIR})
```

2024-01-19 14:51 UTC, caic99 approved these changes

2024-01-19 14:51 UTC, caic99 commented on Dockerfile.gnu
> +    libxc-dev libgtest-dev libgmock-dev libbenchmark-dev python3-numpy \
Please also update docs. Thanks!

2024-01-22 03:38 UTC, jieli-matrix commented on Dockerfile.gnu
> +    libxc-dev libgtest-dev libgmock-dev libbenchmark-dev python3-numpy \
Done!

2024-01-25 06:51 UTC, caic99 commented
@jieli-matrix I suggest putting benchmark test in the existed integrated test process, avoid overheads. Maybe in some day we have enough tests, we could separate them into a workflow, and run routinely.

2024-01-25 10:42 UTC, caic99 commented on .github/workflows/test.yml
> +          cmake -B build -DENABLE_GOOGLEBENCH=ON -DENABLE_DEEPKS=ON -DENABLE_LIBXC=ON -DENABLE_LIBRI=ON -DENABLE_PAW=ON
```suggestion
          cmake -B build -DBUILD_TESTING=ON -DENABLE_DEEPKS=ON -DENABLE_LIBXC=ON -DENABLE_LIBRI=ON -DENABLE_PAW=ON -DENABLE_GOOGLEBENCH=ON
```

2024-01-26 03:26 UTC, caic99 approved these changes
LGTM

2024-01-26 04:01 UTC, merged