Feature: support double_grid in `mix_rho_recip_new()`
deepmodeling/abacus-develop pull request #3577
Opened 2024-01-31 08:30 UTC by WHUweiqingzhou

Fix #3520.

1. Based on `mix_rho_recip()`, support `Global::double_grid` in `mix_rho_recip_new()` as well.
2. For easy code review, I do not delete `mix_rho_recip()` at this PR. I will make another PR to delete it once this PR is merged.

2024-01-31 17:19 UTC, YuLiu98 requested changes
It seems that the PR reports a warning about the test `101_PW_upf201_uspp_Fe`. Maybe there is something wrong?

2024-02-01 02:53 UTC, WHUweiqingzhou commented
> It seems that the PR reports a warning about the test `101_PW_upf201_uspp_Fe`. Maybe there is something wrong?

@YuLiu98,
Since before this PR, uspp calculations use old mixing `mixing_rho_recip()`. This PR enables the new mixing method also supports uspp calculations, where the charge density and magnetic density is mixed separately. We get the same result as the one from old mixing by setting `mixing_beta=mixing_beta=mag` and `mixing_gg0=mixing_gg0_mag` manually.
I have pulled a new commit to change the INPUT from:
```cpp
mixing_beta            0.4
```
into
```cpp
mixing_beta            0.4
mixing_beta_mag        0.4
mixing_gg0             1.0
mixing_gg0_mag         1.0
```
After that, we can fix this warning.

2024-02-01 18:59 UTC, YuLiu98 approved these changes

2024-02-02 07:42 UTC, dyzheng approved these changes
LGTM

2024-02-02 07:42 UTC, merged