Change pointers to vectors
deepmodeling/abacus-develop pull request #3980
Opened 2024-04-14 13:38 UTC by DylanWRh

Change some pointers to vectors in formatter_contextfmt_test.cpp

2024-04-15 01:22 UTC, kirk0830 commented on source/module_base/test/formatter_contextfmt_test.cpp
No, please do not change this function. Try to look at the name of this test case: `StreamOperatorLeft2PtrInt`, it is, test of stream operator left (<<) to pointer/array of int

2024-04-15 01:24 UTC, kirk0830 approved these changes

2024-04-15 01:37 UTC, DylanWRh commented on source/module_base/test/formatter_contextfmt_test.cpp
Alright. I'll try to find out other pointers that could be replaced by vectors. Thanks for the tip!

2024-04-15 01:56 UTC, DylanWRh commented on source/module_base/test/formatter_contextfmt_test.cpp
> No, please do not change this function. Try to look at the name of this test case: `StreamOperatorLeft2PtrInt`, it is, test of stream operator left (<<) to pointer/array of int

Alright. I'll try to find out other pointers that could be replaced by vectors. Thanks for the tip!

2024-04-15 02:28 UTC, kirk0830 requested changes
cubsplin is the part used to be refactoed by @jinzx10, ask for comments from him would be safe and beneficial.

2024-04-15 02:28 UTC, kirk0830 commented on source/module_base/cubic_spline.cpp
> -        double* dx = new double[n - 1];
I remember you used to refactor this part, I wonder way you did not use std::vector then? Do you have some special consideration? About heterogeneous calculation? @jinzx10

2024-04-15 06:25 UTC, jinzx10 approved these changes

2024-04-15 06:56 UTC, kirk0830 approved these changes

2024-04-16 13:23 UTC, mohanchen approved these changes

2024-04-16 13:23 UTC, merged