Perf: Optimize `hsolver` GPU code
deepmodeling/abacus-develop pull request #4295
Opened 2024-06-03 03:15 UTC by OldDriver233

### What's changed?
- Unrolling loops. As code in a wrap uses SIMD, no `__syncthreads()` is needed.
- Adjusting `vector` operations. Currently the operations used too less blocks(typically < 20), causing waste of SMs.

2024-06-03 05:11 UTC, dyzheng requested changes

2024-06-03 05:11 UTC, dyzheng commented on source/module_hsolver/kernels/cuda/math_kernel_op.cu
> +const int WARP_SIZE = 32;
In this PR, you have changed the macro to const variables, the name of variables should be lower-case instead of upper-case.

2024-06-03 05:11 UTC, dyzheng commented on source/module_hsolver/kernels/cuda/math_kernel_op.cu
> +    for (int ii = THREAD_PER_BLOCK >> 1; ii > WARP_SIZE; ii >>= 1) {
In this PR, you have optimized the performance of this code, please add annotations to explain the reason.

2024-06-03 05:11 UTC, dyzheng commented on source/module_hsolver/kernels/cuda/math_kernel_op.cu
> +    if (tid < WARP_SIZE) {
In this PR, you have optimized the performance of this code, please add annotations to explain code below.

2024-06-03 05:11 UTC, dyzheng commented on source/module_hsolver/kernels/cuda/math_kernel_op.cu
> +const int THREAD_PER_BLOCK = 256;
Please add namespace for these const variables.

2024-06-03 05:30 UTC, OldDriver233 commented
@dyzheng the issues mentioned above are solved in commit `40f973f`.

2024-06-03 06:44 UTC, dyzheng reviewed
The remain question is that can you list some test result to verify your code can improve the performance in PR description?

2024-06-03 07:17 UTC, caic99 approved these changes

2024-06-03 08:22 UTC, OldDriver233 commented
> The remain question is that can you list some test result to verify your code can improve the performance in PR description?

Yes. For vector functions the change had been obvious.

- Before the change:
![before](https://github.com/deepmodeling/abacus-develop/assets/23579428/d55d3113-0eec-4a77-a679-991ec673f118)

- After the change:
![after](https://github.com/deepmodeling/abacus-develop/assets/23579428/d2539d1a-a62a-47c5-8393-b6b50f0e77ab)

2024-06-03 08:37 UTC, OldDriver233 commented
For `line_minimize` and `calc_grad` the difference is minor.

- Before:
![before](https://github.com/deepmodeling/abacus-develop/assets/23579428/71af1601-3a38-4830-9b7d-fa5755f25311)

- After:
![after](https://github.com/deepmodeling/abacus-develop/assets/23579428/ca023589-261e-46bf-8456-5bf0c7264472)

2024-06-03 08:40 UTC, OldDriver233 commented
N.B. the testing case is `./examples/gpu/si16_pw`, running on `NVIDIA GeForce RTX 3070 Mobile / Max-Q`.

2024-06-03 08:45 UTC, denghuilu commented
Excellent! It would be better to tell us about the software and hardware infos used in your benchmarks.

2024-06-03 09:42 UTC, dyzheng approved these changes

2024-06-03 10:12 UTC, caic99 commented
@OldDriver233 What tools are you using for profiling & visualizing those results? That looks really cool.

2024-06-03 10:51 UTC, OldDriver233 commented
> @OldDriver233 What tools are you using for profiling & visualizing those results? Is that nsight compute? That looks really cool.

Yes. In nsight compute, you can filter out kernel functions you wish to profile, which is a useful feature.

2024-06-04 02:11 UTC, haozhihan reviewed
LGTM

2024-06-04 02:12 UTC, haozhihan approved these changes
LGTM

2024-06-04 02:27 UTC, haozhihan commented
By the way, because we are working on first-principles calculation software, the cases of calculations are often very different, including large cases and small cases.

When we talk about performance improvement, if we only focus on one case (or even one kernel), it is not very convincing.

When @denghuilu and I (@haozhihan) were developing GPU code before, we needed to conduct system testing (many cases covering various systems) to convince @mohanchen that our code performance had greatly improved.

Considering this, should we specify a process to prove performance improvement so that external developers can better participate in the performance improvement of ABACUS?

There really was no external developer contributing code for performance improvements in ABACUS before.

So thanks again to @OldDriver233.

2024-06-05 12:36 UTC, OldDriver233 commented
[testcase.zip](https://github.com/user-attachments/files/15586878/testcase.zip)
Here is the testing result of 10 cases. Note that my computer(With `NVIDIA GeForce RTX 3070 Mobile / Max-Q`) reported out-of-memory on testcase 009, so this case is not tested.

For the 9 cases, `vector` related functions appeared to be faster than the original program in most cases. In case 007 the difference appears to be the biggest: 495008 vs. 523616, about 5% difference.

But for `calc_grad` and `line_minimize`, situation becomes different. For small cases they are *slightly* faster, but for bigger cases they became slower. I suppose that my card does not have enough fp64 units, resulting in the difference.

2024-06-08 07:43 UTC, mohanchen approved these changes

2024-06-08 07:44 UTC, mohanchen commented
LGTM

2024-06-08 07:44 UTC, merged