Refactor and Optimize: Function Encapsulation and Dynamic Scheduling Enhancements
deepmodeling/abacus-develop pull request #4403
Opened 2024-06-15 21:23 UTC by Esperanzalukas

- Refactored code by encapsulating common functionalities into a reusable function `process_sparse_matrix`.
- The `process_sparse_matrix` function now supports both general sparse matrix processing and specific `dim`-based distribution.
- Introduced dynamic scheduling with adjustable block sizes to optimize parallel computations, leveraging the number of available threads to set appropriate chunk sizes.

2024-06-17 22:53 UTC, mohanchen approved these changes

2024-06-18 08:46 UTC, dyzheng requested changes

2024-06-18 08:46 UTC, dyzheng commented on source/module_hamilt_lcao/module_gint/gint_k.h
> +                    if (trace_lo[row] >= 0)  // 使用类成员变量 trace_lo
Please use English for comments.

2024-06-18 08:46 UTC, dyzheng commented on source/module_hamilt_lcao/module_gint/gint_k.h
> +inline void Gint_k::process_sparse_matrix(
Please don't add function with definition in *.h, you can move it to *.hpp.

2024-06-18 09:00 UTC, mohanchen commented
Since the class is over, I will close this PR. New PR is welcome.

2024-06-18 09:00 UTC, closed without merging