Feature: read a slice of bands from WFC_NAO files & enable custom number of occupied bands near HOMO
deepmodeling/abacus-develop pull request #4691
Opened 2024-07-13 19:43 UTC by maki49

Fix #4690 
Link #2460 

In the previous LR-TDDFT code, `nocc` is calculated directly from the number of electrons. However, if low excitation states are solved, we can use less occupied bands close to HOMO. 
@dyzheng Thanks for such a good suggestion.
@jinzx10 Thanks for informing us `Cpxgemr2d`, there's a local-to-local usage in this PR.

2024-07-13 23:06 UTC, mohanchen approved these changes

2024-07-14 02:24 UTC, Qianruipku requested changes

2024-07-14 02:24 UTC, Qianruipku commented on source/module_io/read_input_item_other.cpp
> +        item.reset_value = [](const Input_Item& item, Parameter& para) {
Please add Uts in read_input_item_test.cpp to ensure this code is covered in tests.
It is also better to add this parameter in read_input_ptest.cpp

2024-07-14 06:56 UTC, Qianruipku approved these changes

2024-07-14 08:39 UTC, merged