Docs: add docs for running_scf.log file in docs/advanced/input_files.
deepmodeling/abacus-develop pull request #4771
Opened 2024-07-23 08:39 UTC by JohnYan98

### Linked Issue
Fix #4732

### Unit Tests and/or Case Tests for my changes
-

### What's changed?
Add docs for runing_scf.log file in docs/advanced/input_files.

### Any changes of core modules? (ignore if not applicable)
No

2024-07-24 02:08 UTC, WHUweiqingzhou reviewed
Please move this docs to output dir

2024-07-24 02:30 UTC, WHUweiqingzhou requested changes
Please add this docs into index file *.rst

2024-07-24 02:54 UTC, caic99 requested changes
Please change the file name to runNing_scf

2024-07-24 05:45 UTC, caic99 approved these changes

2024-07-28 09:54 UTC, WHUweiqingzhou approved these changes
LGTM.

2024-07-28 10:44 UTC, merged