Use lambda expressions to reduce if conditions.
deepmodeling/abacus-develop pull request #4828
Opened 2024-07-29 16:01 UTC by grysgreat

lambda expressions are used in the gpu/dcu modules of hamilt-stress and force to reduce the judgment conditions in the operator.

After testing, the operator execution time is almost unchanged after introducing lambda expressions (from `0.08+-0.02` to `0.08+-0.02`).

### Linked Issue
Fix #4823

2024-07-30 05:18 UTC, dzzz2001 approved these changes

2024-07-30 08:06 UTC, dzzz2001 commented on source/module_hamilt_pw/hamilt_pwdft/kernels/cuda/stress_op.cu
>      FPTYPE aux_d[2];
aux_d[2] seems to be redundant here

2024-07-30 08:12 UTC, dzzz2001 requested changes

2024-07-30 08:12 UTC, dzzz2001 commented on source/module_hamilt_pw/hamilt_pwdft/kernels/cuda/stress_op.cu
>      FPTYPE aux_d[2];
"FPTYPE aux_d[2]" seems redundant here.

2024-07-30 13:50 UTC, dzzz2001 approved these changes

2024-08-01 02:26 UTC, dyzheng approved these changes

2024-08-01 02:26 UTC, merged