Refactor
deepmodeling/abacus-develop pull request #5053
Opened 2024-09-05 04:08 UTC by A-006

### Reminder
- [ ] Have you linked an issue with this pull request?
- [ ] Have you added adequate unit tests and/or case tests for your pull request?
- [ ] Have you noticed possible changes of behavior below or in the linked issue?
- [ ] Have you explained the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi? (ignore if not applicable)

### Linked Issue
Fix #...

### Unit Tests and/or Case Tests for my changes
- A unit test is added for each new feature or bug fix.

### What's changed?
- Example: My changes might affect the performance of the application under certain conditions, and I have tested the impact on various scenarios...

### Any changes of core modules? (ignore if not applicable)
- Example: I have added a new virtual function in the esolver base class in order to ...

2024-09-09 01:40 UTC, Qianruipku requested changes

2024-09-09 01:40 UTC, Qianruipku commented on source/module_io/read_input_item_other.cpp
> -    }
Please remove colour in input-main.md

2024-09-09 01:40 UTC, Qianruipku commented on source/module_parameter/input_parameter.h
> +#include "module_parameter/parameter.h"
delete it

2024-09-09 12:00 UTC, A-006 commented on source/module_io/read_input_item_other.cpp
> -    }
the problem has been finished

2024-09-09 12:05 UTC, A-006 commented on source/module_parameter/input_parameter.h
> +#include "module_parameter/parameter.h"
The problem has been finished

2024-09-10 07:04 UTC, Qianruipku approved these changes

2024-09-10 07:04 UTC, merged