Refatcor:Use PARAM instead of GlobalV::NBAND,NLocal
deepmodeling/abacus-develop pull request #5193
Opened 2024-09-29 09:42 UTC by A-006

### Linked Issue
close #5137
### Unit Tests and/or Case Tests for my changes
- Change the Unit test of the nband,nlocal,nelec,updown

### What's changed?
- As the last PR of the #5137,the last parameters has been changed in the program.

2024-09-30 09:00 UTC, Qianruipku requested changes

2024-09-30 09:00 UTC, Qianruipku commented on source/module_cell/cal_atoms_info.h
> -                    GlobalV::nupdown += atoms[it].mag[ia];
In this function, we have Parameter& para. Use para instead of PARAM.

2024-10-01 01:30 UTC, A-006 commented on source/module_cell/cal_atoms_info.h
> -                    GlobalV::nupdown += atoms[it].mag[ia];
The problem has been solved.

2024-10-04 03:13 UTC, Qianruipku approved these changes

2024-10-05 07:11 UTC, mohanchen approved these changes

2024-10-10 04:49 UTC, merged