Refactor namespace Exx_Opt_Orb
deepmodeling/abacus-develop pull request #5226
Opened 2024-10-13 14:58 UTC by PeizeLin

2024-10-15 06:05 UTC, kirk0830 requested changes
this PR do some minor refactor on codes that add "this->" to instance named "orb_", which makes the code clearer, this is acceptable.
However, it also shows me very astonishing use of nested std::map (I had never known them before), and very long lambda function that makes me confused about the program design. 
There are also parameters packed in struct and named as "info", which I think, will bring more difficulty on program maintainment, so I request a change on it.
 
The use of extern keyword seems confusing and needs more explanation.

There are also new code added which depends explicitly on instance of class LCAO_Orbitals (is it a to-be-deprecated class? @mohanchen ).

Because seems there are already many codes in this module, so an immediate thoroughful improvement on code structure is nearly impossible, I recommend not introduce more cognition complexity into codes.

2024-10-15 06:05 UTC, kirk0830 commented on source/module_io/input_conv.cpp
> +        GlobalC::exx_info.info_opt_abfs.abfs_Lmax = PARAM.inp.exx_opt_orb_lmax;
use of GlobalC is highly discouraged

2024-10-15 06:05 UTC, kirk0830 commented on source/module_ri/exx_abfs-construct_orbs.h
> +	extern std::vector<std::vector<std::vector<Numerical_Orbital_Lm>>> change_orbs(
could you explain why you change all `static` to `extern`???
from https://en.cppreference.com/w/cpp/keyword/extern, which is the result want to get?

2024-10-15 06:05 UTC, kirk0830 commented on source/module_ri/exx_abfs-jle.cpp
> +	const Exx_Info::Exx_Info_Opt_ABFs &info,
the "info" used here has very straight forward drawback: it is impossible to know what one function really needs according to its parameter list. This will brings difficulty to code maintaining, unless this code is not expected to be maintained by any other

2024-10-15 06:05 UTC, kirk0830 commented on source/module_ri/exx_opt_orb-print.cpp
>  	auto print_header = [&]( std::ofstream &ofs )
why use lambda here?

2024-10-15 06:05 UTC, kirk0830 commented on source/module_ri/exx_opt_orb-print.cpp
>  	auto print_Q = [&]( std::ofstream &ofs )
why use lambda here?

2024-10-15 08:08 UTC, PeizeLin commented
> this PR do some minor refactor on codes that add "this->" to instance named "orb_", which makes the code clearer, this is acceptable. However, it also shows me very astonishing use of nested std::map (I had never known them before), and very long lambda function that makes me confused about the program design. There are also parameters packed in struct and named as "info", which I think, will bring more difficulty on program maintainment, so I request a change on it.
> 
> The use of extern keyword seems confusing and needs more explanation.
> 
> There are also new code added which depends explicitly on instance of class LCAO_Orbitals (is it a to-be-deprecated class? @mohanchen ).
> 
> Because seems there are already many codes in this module, so an immediate thoroughful improvement on code structure is nearly impossible, I recommend not introduce more cognition complexity into codes.

This PR is just to fix this code from at least five years ago, making it can be run again under the LibRI framework. Many years ago, the code of exx without LibRI was completely different from today.
So if you want to make more modifications to this code, I think it's better to be put in the future PR.

2024-10-15 09:02 UTC, kirk0830 commented
@PeizeLin Hi, I understand the historical reason you mentioned.
There are reasons why I call "info" brings difficulty on code maintainment:
1. As the rule of thumb, functions should only take variables they really need, otherwise all possible caller will have an unnecessary long parameter list, or say it appears to be something like other developers are forced to know about exx_info instead of merely understand the function itself
2. a single call to function whose parameter list have an exx_info datatype obj, should be behind the construction of exx_info, or an explicit inclusion of file exx_info.h, this means a strong coupling between struct exx_info and functions. This will bring inconvienence on unittest which partially ensuring the function can work as expected.

2024-10-18 15:12 UTC, PeizeLin commented
> @PeizeLin Hi, I understand the historical reason you mentioned. There are reasons why I call "info" brings difficulty to code maintainment:
> 
> 1. As the rule of thumb, functions should only take variables they really need, otherwise all possible caller will have an unnecessary long parameter list, or say it appears to be something like other developers are forced to know about exx_info instead of merely understand the function itself
> 2. a single call to function whose parameter list have an exx_info datatype obj, should be behind the construction of exx_info, or an explicit inclusion of file exx_info.h, this means a strong coupling between struct exx_info and functions. This will bring inconvienence on unittest which partially ensuring the function can work as expected.

All the variables in `info` is needed in the function. They come from INPUT.
I think it's better to use this four variables struct as the function parameter explicitly than use the static variable `PARAM.inp`?

2024-11-06 11:07 UTC, PeizeLin commented on source/module_ri/exx_opt_orb-print.cpp
>  	auto print_header = [&]( std::ofstream &ofs )
updated

2024-11-06 11:07 UTC, PeizeLin commented on source/module_ri/exx_opt_orb-print.cpp
>  	auto print_Q = [&]( std::ofstream &ofs )
updated

2024-11-07 13:12 UTC, kirk0830 reviewed
I retract my file change request presently

2024-11-14 13:47 UTC, mohanchen commented
I have seen new PR, so this one will be closed.

2024-11-14 13:47 UTC, closed without merging