<Test>: add the unit test of module_orbital
deepmodeling/abacus-develop pull request #634
Opened 2022-01-13 12:53 UTC by maki49

- Add `cal_grad_overlap` in Center2_orb::Orb11 
    - (have passed the double check with module_orbital)
- Add unit test of module_orbital
    - ORB_gen_tables::snap_psipsi(job=0) equals to Center2_Orb::Orb11::cal_overlap
    - ORB_gen_tables::snap_psipsi(job=1) equals to Center2_Orb::Orb11::cal_grad_overlap

2022-01-13 15:15 UTC, caic99 commented
Hi @maki49 ,
Thank you for your PR! However, you might not noticed the latest doc on [adding UTs]( https://github.com/deepmodeling/abacus-develop/blob/develop/doc/developers.md#add-a-unit-test). Please follow the doc, which requires little based on your branch. Generally, you should move test codes to a dedicated place, and add CMake support to test programs.

2022-01-14 03:52 UTC, maki49 commented
I've moved the test and compiled it with cmake. But when I run it, an Error occured : “Attempting to use an MPI routine before initializing MPICH”. What should I do to solve it (may be add something to which `CMakeLists.txt` file)? 
![image](https://user-images.githubusercontent.com/33978601/149448305-db1464bf-91d0-44f0-9cb9-48595bfe503c.png)

2022-01-18 07:04 UTC, caic99 commented
> I've moved the test and compiled it with cmake. But when I run it, an Error occured : “Attempting to use an MPI routine before initializing MPICH”. What should I do to solve it (may be add something to which `CMakeLists.txt` file)? When I make with module_orbital/test/Makefile, it can run and pass. ![image](https://user-images.githubusercontent.com/33978601/149448305-db1464bf-91d0-44f0-9cb9-48595bfe503c.png)

Hi @maki49 ,
You might perform `MPI_Init` in main function. See https://github.com/deepmodeling/abacus-develop/pull/625 for implementation details.

2022-01-22 09:05 UTC, maki49 commented
![image](https://user-images.githubusercontent.com/33978601/150632155-f1f65165-9901-4ee9-bd4a-f490a65e78cc.png)
What is "Child Killed" mean ? I'm confused....

2022-01-24 03:29 UTC, caic99 commented on source/module_orbital/CMakeLists.txt
> +  set(CMAKE_CXX_STANDARD 14)
Would you move this line above to 
https://github.com/deepmodeling/abacus-develop/blob/b6e9a7ec60d3a9106b25ab7da947508ce218ded9/CMakeLists.txt#L233

2022-01-24 03:29 UTC, caic99 commented on source/module_orbital/test/1_snap_equal_test.cpp
> +    int result = RUN_ALL_TESTS();
Don't forget to `return result;` for `int main()`.
https://google.github.io/googletest/reference/testing.html#RUN_ALL_TESTS

2022-01-24 03:29 UTC, caic99 commented on source/src_lcao/center2_orb-orb11.cpp
> +    const int& mA, const int& mB) const
You are mixing space and tab for indentation. Same as line 159-160.

2022-01-24 03:29 UTC, caic99 commented on source/src_lcao/center2_orb-orb11.cpp
> +    const double tiny1 = 1e-12;		// why 1e-12?
Yes, why we choose this standard? You might figure it out with someone in charge.

2022-01-24 03:29 UTC, caic99 commented on source/src_lcao/center2_orb-orb11.cpp
> +	if( distance > (RcutA + RcutB) ) return 0.0;
Sorry but does `0.0` matches returning type `ModuleBase::Vector3<double>` well?

2022-01-24 03:34 UTC, caic99 commented
> ![image](https://user-images.githubusercontent.com/33978601/150632155-f1f65165-9901-4ee9-bd4a-f490a65e78cc.png) What is "Child Killed" mean ? I'm confused....

Hi @maki49 ,
this error message might means your MPI child process failed to execute. From my point of view, it's still a "child" although on its own.

2022-01-30 03:35 UTC, caic99 commented
Hi @maki49 ,
Will you follow up changes on UT pipeline in #676 ? Thanks.

2022-02-08 14:30 UTC, maki49 commented
I‘ve updated according to #676, but still "child killed".... 
It's ok on my work station, compiled by whether cmake or Makefile.

2022-02-09 05:48 UTC, caic99 commented
> I‘ve updated according to #676, but still "child killed".... It's ok on my work station, compiled by whether cmake or Makefile.

Hi @maki49 ,
I create a testing environment by myself and reproduced the problem. 
The CI pipeline will install tests to `build/tests` before they are executed.
https://github.com/deepmodeling/abacus-develop/blob/adc3b67e2ed84eb274387e018732268a6e7326a7/.github/workflows/test.yml#L52
Hence, the test is executed under `build/tests/`. However, you refer to `GaAs` folder by relative path, producing 
> ../../../../source/module_orbital/test/GaAs/STRU
ERROR : file STRU does not exist

Appending `install(DIRECTORY GaAs DESTINATION ${CMAKE_CURRENT_BINARY_DIR}/../../../tests)` after 
https://github.com/maki49/abacus-develop/blob/238828a4eb3fd1d0484e95964e033fe720bb5c75/source/module_orbital/test/CMakeLists.txt#L39-L44
works fine to me.

2022-02-09 07:32 UTC, maki49 commented
> 

I've added, now it seems the needed file is found, but still 'child killed' ...

2022-02-10 04:15 UTC, caic99 commented
> > 
> 
> I've added, now it seems the needed file is found, but still 'child killed' ...

Sorry, it seems that the problem does not  lies there. I'll look into it these days.

2022-02-11 07:17 UTC, caic99 commented
Hi @maki49 ,
I've located the problem. It's quite complicated.
In ORB_unittest.cpp `void test_orb::set_orbs`: 	[`const Numerical_Nonlocal beta_[1];`](https://github.com/maki49/abacus-develop/blob/e31807d0ac9dd44dce9e973ebb5f326bb1c52954/source/module_orbital/test/ORB_unittest.cpp#L90) while there are two elements in this system. This leads to an illegal memory access when doing `cal_Lmax_Beta` (ORB_table_phi.cpp:L805), resulting an extremely large `Lmax`.
In `Sph_Bessel_Recursive::D2::cal_jlx_smallx`, it requires a minimum of 43692\*3005\*1005 (l_size * ix1_size * ix2_size) integers. Then the program failed because of OOM.

2022-02-11 07:41 UTC, maki49 commented
> 

Thanks for debugging ~ I think it may caused by the uninitialized `lmax` in `ORB_nonlocal.h`. I initialized it to zero.  It needs to be CI-tested again after "security token invalid" problem is solved.

2022-02-11 07:51 UTC, caic99 commented
> > 
> 
> Thanks for debugging ~ I think it may caused by the uninitialized `lmax` in `ORB_nonlocal.h`. I initialized it to zero. It needs to be CI-tested again after "security token invalid" problem is solved.

@maki49 
I'm sorry but I still can not understand, why does the uninitialized `lmax` caused it? You've accessed `beta[ntype=1]`, while your code only allocated `beta[1]`.

2022-02-11 07:55 UTC, maki49 commented
> > > 
> > 
> > 
> > Thanks for debugging ~ I think it may caused by the uninitialized `lmax` in `ORB_nonlocal.h`. I initialized it to zero. It needs to be CI-tested again after "security token invalid" problem is solved.
> 
> @maki49 I'm sorry but I still can not understand, why does the uninitialized `lmax` caused it? You've accessed `beta[ntype=1]`, while your code only allocated `beta[1]`.

Yes, it's my fault. I've fixed it.

2022-02-11 07:56 UTC, caic99 commented on source/module_orbital/test/ORB_unittest.cpp
> +	const Numerical_Nonlocal beta_[2];
Maybe it should be `ORB.get_ntype()`, rather than a magic number '2'?

2022-02-11 08:01 UTC, maki49 commented on source/module_orbital/test/ORB_unittest.cpp
> +	const Numerical_Nonlocal beta_[2];
> Maybe it should be `ORB.get_ntype()`, rather than a magic number '2'?

Thanks.( Sorry because I was so careless...

2022-02-11 08:04 UTC, caic99 commented
And I still wonder why Address Sanitizer is failed to report such a simple array access out of bound issue.

2022-02-11 16:44 UTC, caic99 requested changes

2022-02-11 16:44 UTC, caic99 commented on source/module_orbital/test/ORB_unittest.h
> +#ifndef _ORBTEST_
The header protection macro should be the same as file name, i.e. `ORB_UNITTEST` here.

2022-02-11 16:44 UTC, caic99 commented on source/module_orbital/test/ORB_unittest.h
> +#include "../../../source/module_base/global_function.h"
Please use absolute path. `module_orbital/ORB_control.h` should work.

2022-02-13 14:04 UTC, caic99 approved these changes

2022-02-13 14:05 UTC, merged