Refactor: implement dm2d directly from `wfc_dm_2d.wfc_k` which have replaced `set_EDM_k`
deepmodeling/abacus-develop pull request #699
Opened 2022-02-11 03:42 UTC by maki49

Now I still keep `set_EDM_k` and `WFC_K_aug` remained (but not called because of the default `new_dm=1`). 
Test have passed on 1/4/5 cores (`*_NO_KP_*` cases).
Multi-k-DeePKS tests are still needed. If passed, I will **delete** `set_EDM_k` and `WFC_K_aug`.

2022-02-11 04:03 UTC, maki49 commented
@caic99 Sorry, but how to solve this problem?
 (This problem occured after I modified a test case, now I've reverted it, but the problem is still here. )
![image](https://user-images.githubusercontent.com/33978601/153535626-d4381eef-f4ce-4ff5-8402-169c278f5d92.png)

2022-02-11 04:12 UTC, caic99 commented
> @caic99 Sorry, but how to solve this problem? (This problem occured after I modified a test case, now I've reverted it, but the problem is still here. ) ![image](https://user-images.githubusercontent.com/33978601/153535626-d4381eef-f4ce-4ff5-8402-169c278f5d92.png)

Hi @maki49 ,
This is not your fault. Our AWS credential for CI machine is expired. We'll use an alternative solution for that.
cc @Unboundwill

2022-02-11 16:43 UTC, caic99 commented on source/src_lcao/FORCE_k.cpp
> +#include "wfc_dm_2d.h"  //caoyu add 2022-2-9
No author and date info needed in code, for `git blame` is in charge of querying such info.

2022-02-12 02:36 UTC, maki49 commented
207_NO_KP_OD occationally fails on CI, but never failed on my workstation. I will report it in issue #707

2022-02-12 05:26 UTC, closed without merging

2022-02-12 05:38 UTC, dyzheng requested changes

2022-02-12 05:38 UTC, dyzheng commented on source/src_lcao/FORCE_k.cpp
> +    if (INPUT.new_dm > 0 && INPUT.tddft==0)
INPUT.tddft has converted to ELEC_evolve::tddft, please use the latter.

2022-02-12 05:38 UTC, dyzheng commented on source/src_lcao/FORCE_k.cpp
> +        ModuleBase::timer::tick("Force_LCAO_k","cal_edm_2d");
If developer want to trace time for this code block, why not use a new inline function here? Too many lines in one function is not good for reading or testing.

2022-02-12 05:38 UTC, dyzheng commented on source/src_lcao/local_orbital_charge.cpp
> +            wfc_dm_2d.wfc_k,
Pay attention on the code indentations.

2022-02-12 05:38 UTC, dyzheng commented on source/src_lcao/wfc_dm_2d.cpp
> +    static int istep=0;
In this file, some code has been repeated at lease twice, maybe developer should use inline function for that, and annotation is important either.

2022-02-12 05:38 UTC, dyzheng commented on source/src_lcao/wfc_dm_2d.cpp
> +    std::ofstream ofs("wfc_"+ModuleBase::GlobalFunc::TO_STRING(istep++)+"_"+ModuleBase::GlobalFunc::TO_STRING(GlobalV::MY_RANK));
This line has a new file open, but where dos this file close?

2022-02-12 05:38 UTC, dyzheng commented on source/src_lcao/wfc_dm_2d.cpp
> +void Wfc_Dm_2d::cal_dm(const ModuleBase::matrix& wg,    // wg(ik,ib), cal all dm
This function looks similar with the function above, why not use template to combine these two functions?

2022-02-12 05:38 UTC, dyzheng commented on source/src_lcao/wfc_dm_2d.cpp
> +    ModuleBase::TITLE("Wfc_Dm_2d", "cal_dm_R");
Looks like there is missing a line of timer::tick.