test: UT and annotations in mathzone_add1
deepmodeling/abacus-develop pull request #728
Opened 2022-02-17 07:48 UTC by hongriTianqi

2022-02-17 08:26 UTC, caic99 requested changes

2022-02-17 08:26 UTC, caic99 commented on source/module_base/test/mathzone_add1_test.cpp
> +		delete[] r_in;
`TearDown()` should be the counterpart of `SetUp()`. However, `r_in` is defined as class member, and this usage may cause memory leak in production code. If you wish to do so, `new double[nr_in]` should be within the constructor of  `class MathzoneAdd1Test`, and `delete` in destructor. Here, a better solution is allocating memory in `SetUp()`.

2022-02-17 08:56 UTC, dyzheng approved these changes

2022-02-18 02:41 UTC, caic99 approved these changes

2022-02-18 03:21 UTC, merged