Refactor : refactor md input parameters
deepmodeling/abacus-develop pull request #764
Opened 2022-03-02 01:23 UTC by YuLiu98

2022-03-02 03:27 UTC, caic99 commented
Hi @YuLiu98 ,
Will you provide a detailed information on this change? If it is the same with issue contents, you can paste them here.
Besides, is there any scripts for users converting current input format to the new one? It seems that there's no backward compatiable in this version, and this change might make the former keys unavailable. cc @wenfei-li @ouqi0711

2022-03-02 05:23 UTC, dyzheng requested changes

2022-03-02 05:23 UTC, dyzheng commented on doc/examples/tddft.md
>  md_mdoutpath mdtest
this parameter is not used now，please delete it from document.

2022-03-02 05:23 UTC, dyzheng commented on doc/examples/tddft.md
>  md_fixtemperature 20000
this parameter is not used now，please delete it from document.

2022-03-02 05:23 UTC, dyzheng commented on doc/examples/tddft.md
>  md_nresn 3
this parameter is not used now，please delete it from document.

2022-03-02 05:23 UTC, dyzheng commented on doc/examples/tddft.md
>  md_nyosh 3
this parameter is not used now，please delete it from document.

2022-03-02 07:11 UTC, YuLiu98 commented
> Will you provide a detailed information on this change? If it is the same with issue contents, you can paste them here.
> Besides, is there any scripts for users converting current input format to the new one? It seems that there's no backward compatiable in this version, and this change might make the former keys unavailable. cc @wenfei-li @ouqi0711

OK, I attached the scripts for users converting current input format to the new one as below.

[input_update.zip](https://github.com/deepmodeling/abacus-develop/files/8167402/input_update.zip)

2022-03-06 01:34 UTC, mohanchen approved these changes
I am OK with these changes.

2022-03-06 02:05 UTC, dyzheng approved these changes

2022-03-06 02:05 UTC, merged