UT of Charge::sum_band()
deepmodeling/abacus-develop pull request #836
Opened 2022-04-14 03:08 UTC by hongriTianqi

2022-04-14 03:47 UTC, caic99 requested changes

2022-04-14 03:47 UTC, caic99 commented on source/src_ri/exx_lcao.h
> +#ifdef __MPI
This change breaks the compilation. Maybe @dyzheng can help.

2022-04-14 03:47 UTC, caic99 commented on source/src_pw/test/CMakeLists.txt
> +install(FILES BANDS_1.dat DESTINATION ${CMAKE_CURRENT_BINARY_DIR})
What does file name means, e.g. `data-H`, `WAVEFUNC1.txt`, `BANDS_1.dat`? You can add some more meaningful prefix/suffix to them.

2022-04-14 03:47 UTC, caic99 commented on source/src_pw/test/CMakeLists.txt
> +  LIBS ${math_libs} base cell symmetry md neighbor orb io ions lcao parallel mrrr pdiag pw ri driver xc ELPA::ELPA esolver
Do we need to link all libs?

2022-04-15 00:54 UTC, closed without merging

2022-04-15 00:56 UTC, hongriTianqi commented
This UT is too involved due to the use of many global class objects. A briefer one is expected to provide.