test: add the unit test of parallel diagonalization by ELPA
deepmodeling/abacus-develop pull request #839
Opened 2022-04-14 06:38 UTC by pxlxingliang

range: source/src_pdiag

2022-04-15 01:50 UTC, caic99 requested changes

2022-04-15 01:50 UTC, caic99 commented on source/src_pdiag/test/diago_elpa_test.cpp
> +    double *e_lapack = 0; // eigenvalues solvered by LAPACK
Typo "solved" here?

2022-04-15 01:50 UTC, caic99 commented on source/src_pdiag/test/diago_elpa_test.cpp
> +    double *e_elpa = 0;
For pointers, please use `nullptr` to initialize.

2022-04-15 01:50 UTC, caic99 commented on source/src_pdiag/test/diago_elpa_test.cpp
> +    double *e_elpa = 0;
For pointers, please use `nullptr` to initialize.

2022-04-19 06:22 UTC, caic99 approved these changes

2022-04-19 06:52 UTC, dyzheng approved these changes

2022-04-19 06:52 UTC, merged