fix: memory leak
deepmodeling/abacus-develop pull request #999
Opened 2022-06-06 14:46 UTC by Qianruipku

1. void getfftixy2is(int*), and add unit test for this function
2. forget to delete pw_wfc in ESolver_KS
for issue：#997

2022-06-06 15:00 UTC, caic99 requested changes
The if statement before delete is not necessary - you can delete a nullptr without side effect. 
[Ref](https://www.cplusplus.com/reference/new/operator%20delete/):"If this is a null-pointer, the function does nothing."

2022-06-06 15:48 UTC, Qianruipku commented
ok

2022-06-07 00:41 UTC, caic99 approved these changes

2022-06-07 03:34 UTC, dyzheng approved these changes

2022-06-07 03:34 UTC, merged